name: Run Digitel Bot

on:
  schedule:
    - cron: '*/30 * * * *'  # ירוץ אוטומטית כל 30 דקות
  workflow_dispatch:        # מאפשר גם להריץ ידנית מתי שתרצי

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 python-telegram-bot

      - name: Run script
        run: python main.py

